name: ieeecrop
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  animated_theme_switcher: ^1.0.5
  simple_animations: ^1.3.3
  http: ^0.12.0+4
  url_launcher: ^5.4.0
  flutter_secure_storage: ^3.3.1+1
  shared_preferences: ^0.5.10
  animations: ^1.1.2
  font_awesome_flutter: ^8.5.0
  image_picker: ^0.6.7+7
  connectivity: ^0.4.9+2
  video_player: ^0.10.12+2
  search_widget: ^1.0.2
  google_fonts: ^1.1.0
  share: ^0.6.4+3
  esys_flutter_share: ^1.0.2
  geolocator: ^6.1.6
  easy_localization: ^2.3.3
  flutter_swiper: ^1.1.6
  webfeed: ^0.4.2
  image: ^2.1.10
  cached_network_image: ^2.0.0
  dio: ^3.0.10
  pretty_dio_logger: ^1.1.1
  giffy_dialog:
  flutter_spinkit: "^4.1.2"
  contactus: ^1.1.7


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_bloc: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages